# API tokens, DB connections, alert channels
github_repo_collector:
    - owner: ivehda-tech
      repo: platformnex-frontend

    - owner: ivehda-tech
      repo: platformnex-backend

    - owner: ivehda-tech
      repo: platformnex-salesforce-frontend

cicd_collector:
    - owner: ivehda-tech
      repo: platformnex-frontend

    - owner: ivehda-tech
      repo: platformnex-backend

    - owner: openai
      repo: openai-agents-js

github_projects_collector:
    - org: ivedha-tech
      project_number: 12

bq_collector:
    - table_name: 'gcp_billing_export_resource_v1_011C19_C13966_9DC5E1'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00

    - table_name: 'gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00

    - table_name: 'gcp_billing_export_v1_011C19_C13966_9DC5E1'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00

    - table_name: 'gcp_billing_export_v1_01E9B5_60A8A4_E1FE52'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00
