# API tokens, DB connections, alert channels
github_repo_collector:
    - owner: ivedha-tech
      repo: platformnex-frontend
      source: github

    - owner: ivedha-tech
      repo: platformnex-backend
      source: github

    - owner: ivedha-tech
      repo: platformnex-salesforce-frontend
      source: github

cicd_collector:
    - owner: ivedha-tech
      repo: platformnex-frontend
      source: github

    - owner: ivedha-tech
      repo: platformnex-backend
      source: github

    - owner: openai
      repo: openai-agents-js
      source: github

github_projects_collector:
    - org: ivedha-tech
      project_number: 12
      source: github

bq_collector:
    - table_name: 'gcp_billing_export_resource_v1_011C19_C13966_9DC5E1'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00
      source: prj-datasource-billing

    - table_name: 'gcp_billing_export_resource_v1_01E9B5_60A8A4_E1FE52'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00
      source: prj-datasource-billing

    - table_name: 'gcp_billing_export_v1_011C19_C13966_9DC5E1'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00
      source: prj-datasource-billing

    - table_name: 'gcp_billing_export_v1_01E9B5_60A8A4_E1FE52'
      dataset_reference: 'prj-datasource-billing.ds_billing'
      platforms:
          - Cloud Build
          - Cloud Run
          - Kubernetes Engine
      start_time: 2026-03-17T00:00:00
      end_time: 2026-03-18T00:00:00
      source: prj-datasource-billing

ENTITY_CONFIG:
    commits:
        table: 'table_github_commits'
    pull_requests:
        table: 'table_github_pull_requests'
    issues:
        table: 'table_github_issues'
    project_items:
        table: 'table_github_projects_data'
    workflow_runs:
        table: 'table_github_workflow_runs'
    deployments:
        table: 'table_github_deployments'
    gcp_logs:
        table: 'table_gcp_bq_data'
